// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

using System;
using Amazon.AuroraDsql.EntityFrameworkCore.Infrastructure;
using Xunit;

namespace Amazon.AuroraDsql.EntityFrameworkCore.IntegrationTests;

/// <summary>
/// Tests dsql-lint binary invocation. No cluster needed — only the bundled native binary.
/// </summary>
public class DsqlLintRunnerTests
{
    [Fact]
    public void FixSql_TransformsSerialType()
    {
        var runner = new DsqlLintRunner();
        var result = runner.FixSql("CREATE TABLE t (id SERIAL PRIMARY KEY);");

        Assert.DoesNotContain("SERIAL", result, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", result, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void FixSql_PassesThroughCleanSql()
    {
        var runner = new DsqlLintRunner();
        var input = "INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\") VALUES ('test');";
        var result = runner.FixSql(input);

        Assert.Contains("INSERT INTO", result);
        Assert.Contains("__EFMigrationsHistory", result);
    }

    [Fact]
    public void FixSql_ThrowsWhenDsqlLintNotFound()
    {
        var runner = new DsqlLintRunner("nonexistent-dsql-lint-binary");
        Assert.Throws<DsqlLintException>(() => runner.FixSql("SELECT 1;"));
    }

    [Fact]
    public void FixSql_ThrowsOnUnfixableSql()
    {
        var runner = new DsqlLintRunner();
        var ex = Assert.Throws<DsqlLintException>(() => runner.FixSql("INVALID SQL GARBAGE @@@;"));

        Assert.Contains("unfixable", ex.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("parse_error", ex.Message);
    }
}