using System.Data.Common;
using Npgsql;

namespace Amazon.AuroraDsql.EntityFrameworkCore.IntegrationTests;

internal static class TestSchemaHelper
{
    private const int MaxRetries = 5;
    public static async Task CreateSchemaAsync(DbDataSource dataSource)
    {
        for (var attempt = 0; attempt <= MaxRetries; attempt++)
        {
            try
            {
                await using var connection = dataSource.CreateConnection();
                await connection.OpenAsync();
                await using var cmd = connection.CreateCommand();

                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS ""Categories"" (
                        ""Id"" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                        ""Name"" character varying(100) NOT NULL
                    )";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS ""Products"" (
                        ""Id"" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                        ""Name"" character varying(200) NOT NULL,
                        ""Price"" numeric NOT NULL,
                        ""Stock"" integer NOT NULL,
                        ""CreatedAt"" timestamp without time zone NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CategoryId"" uuid NOT NULL
                    )";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS ""Counters"" (
                        ""Id"" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (CACHE 65536),
                        ""Name"" character varying(100) NOT NULL
                    )";
                await cmd.ExecuteNonQueryAsync();
                return;
            }
            catch (PostgresException ex) when (ex.SqlState == "40001" && attempt < MaxRetries)
            {
                await Task.Delay(500 * (attempt + 1));
            }
        }
    }

    public static async Task CleanupDataAsync(DbDataSource dataSource)
    {
        for (var attempt = 0; attempt <= MaxRetries; attempt++)
        {
            try
            {
                await using var connection = dataSource.CreateConnection();
                await connection.OpenAsync();
                await using var cmd = connection.CreateCommand();

                cmd.CommandText = "DELETE FROM \"Products\"";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = "DELETE FROM \"Categories\"";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = "DELETE FROM \"Counters\"";
                await cmd.ExecuteNonQueryAsync();
                return;
            }
            catch (PostgresException ex) when (ex.SqlState == "40001" && attempt < MaxRetries)
            {
                await Task.Delay(200 * (attempt + 1));
            }
        }
    }
}
