// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

using System.Data.Common;
using System.Threading;
using Npgsql;

namespace Amazon.AuroraDsql.EntityFrameworkCore.IntegrationTests;

internal static class TestSchemaHelper
{
    private const int MaxRetries = 5;
    private static bool _schemaInitialized;
    private static readonly SemaphoreSlim _lock = new(1, 1);

    public static async Task CreateSchemaAsync(DbDataSource dataSource)
    {
        await _lock.WaitAsync();
        try
        {
            if (_schemaInitialized) return;
            await CreateSchemaCore(dataSource);
            _schemaInitialized = true;
        }
        finally
        {
            _lock.Release();
        }
    }

    private static async Task CreateSchemaCore(DbDataSource dataSource)
    {
        for (var attempt = 0; attempt <= MaxRetries; attempt++)
        {
            try
            {
                await using var connection = dataSource.CreateConnection();
                await connection.OpenAsync();
                await using var cmd = connection.CreateCommand();

                // Drop and recreate to ensure correct schema regardless of prior state
                cmd.CommandText = @"DROP TABLE IF EXISTS ""Products""";
                await cmd.ExecuteNonQueryAsync();
                cmd.CommandText = @"DROP TABLE IF EXISTS ""Categories""";
                await cmd.ExecuteNonQueryAsync();
                cmd.CommandText = @"DROP TABLE IF EXISTS ""Counters""";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = @"
                    CREATE TABLE ""Categories"" (
                        ""Id"" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                        ""Name"" character varying(100) NOT NULL
                    )";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = @"
                    CREATE TABLE ""Products"" (
                        ""Id"" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                        ""Name"" character varying(200) NOT NULL,
                        ""Price"" numeric NOT NULL,
                        ""Stock"" integer NOT NULL,
                        ""CreatedAt"" timestamp without time zone NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CategoryId"" uuid NOT NULL
                    )";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = @"
                    CREATE TABLE ""Counters"" (
                        ""Id"" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (CACHE 65536),
                        ""Name"" character varying(100) NOT NULL
                    )";
                await cmd.ExecuteNonQueryAsync();
                return;
            }
            catch (PostgresException ex) when (ex.SqlState == "40001" && attempt < MaxRetries)
            {
                await Task.Delay(500 * (attempt + 1));
            }
        }
    }

    public static async Task CleanupDataAsync(DbDataSource dataSource)
    {
        for (var attempt = 0; attempt <= MaxRetries; attempt++)
        {
            try
            {
                await using var connection = dataSource.CreateConnection();
                await connection.OpenAsync();
                await using var cmd = connection.CreateCommand();

                cmd.CommandText = "DELETE FROM \"Products\"";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = "DELETE FROM \"Categories\"";
                await cmd.ExecuteNonQueryAsync();

                cmd.CommandText = "DELETE FROM \"Counters\"";
                await cmd.ExecuteNonQueryAsync();
                return;
            }
            catch (PostgresException ex) when (ex.SqlState == "40001" && attempt < MaxRetries)
            {
                await Task.Delay(200 * (attempt + 1));
            }
        }
    }
}