version: 0.2

#env:
  #variables:
     # key: "There are no variables"
  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       python: 3.8
    #commands:
      # - There are no build commands
  pre_build:
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - source $HOME/.cargo/env
      - uv sync --extra test --extra dev
  build:
    commands:
      - uv run pytest aurora_dsql_django/tests/unit/
      - uv run pytest aurora_dsql_django/tests/integration/ -rfs
  post_build:
    commands:
      - uv build
