# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import uuid
from unittest.mock import MagicMock

import pytest
from tortoise import Tortoise, fields
from tortoise.models import Model

from aurora_dsql_tortoise.asyncpg.schema_generator import AuroraDSQLAsyncpgSchemaGenerator
from aurora_dsql_tortoise.psycopg.schema_generator import AuroraDSQLPsycopgSchemaGenerator


class Parent(Model):
    id = fields.UUIDField(primary_key=True, default=uuid.uuid4)
    name = fields.CharField(max_length=100, db_index=True)

    class Meta:
        table = "test_parent"


class Child(Model):
    id = fields.UUIDField(primary_key=True, default=uuid.uuid4)
    parent = fields.ForeignKeyField("models.Parent", related_name="children")

    class Meta:
        table = "test_child"


class BigIntPKModel(Model):
    id = fields.BigIntField(primary_key=True)
    name = fields.CharField(max_length=100)

    class Meta:
        table = "test_bigint_pk"


@pytest.fixture
async def initialized_models():
    """Initialize Tortoise with models but no real DB connection."""
    await Tortoise.init(
        config={
            "connections": {"default": "sqlite://:memory:"},
            "apps": {"models": {"models": [__name__], "default_connection": "default"}},
        }
    )
    yield
    await Tortoise.close_connections()


def _create_mock_client():
    """Create a mock client that matches the default connection for model filtering."""
    connection = Tortoise.get_connection("default")
    mock_client = MagicMock()
    mock_client.schema = None
    type(mock_client).__eq__ = lambda self, other: other == connection
    return mock_client


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "generator_cls", [AuroraDSQLPsycopgSchemaGenerator, AuroraDSQLAsyncpgSchemaGenerator]
)
async def test_schema_excludes_fk_references(initialized_models, generator_cls):
    """Test that generated schema SQL does not contain FK REFERENCES clause."""
    generator = generator_cls(_create_mock_client())
    schema_sql = generator.get_create_schema_sql(safe=True)

    assert "parent_id" in schema_sql, f"Schema should contain FK column:\n{schema_sql}"
    assert "REFERENCES" not in schema_sql, f"Schema should not contain FK REFERENCES:\n{schema_sql}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "generator_cls", [AuroraDSQLPsycopgSchemaGenerator, AuroraDSQLAsyncpgSchemaGenerator]
)
async def test_schema_uses_async_index_creation(initialized_models, generator_cls):
    """Test that CREATE INDEX statements use ASYNC keyword for DSQL."""
    generator = generator_cls(_create_mock_client())
    schema_sql = generator.get_create_schema_sql(safe=True)

    assert "CREATE INDEX ASYNC" in schema_sql, (
        f"Schema should use ASYNC index creation:\n{schema_sql}"
    )
    assert 'ON "test_parent" (' in schema_sql, (
        f"Schema should use the correct table name in index creation:\n{schema_sql}"
    )


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "generator_cls", [AuroraDSQLPsycopgSchemaGenerator, AuroraDSQLAsyncpgSchemaGenerator]
)
async def test_bigint_pk_uses_identity(initialized_models, generator_cls):
    """Test that BigIntField PK uses IDENTITY instead of BIGSERIAL."""
    generator = generator_cls(_create_mock_client())
    schema_sql = generator.get_create_schema_sql(safe=True)

    assert "BIGSERIAL" not in schema_sql, f"Schema should not use BIGSERIAL:\n{schema_sql}"
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema_sql, (
        f"Schema should use IDENTITY for BigIntField PK:\n{schema_sql}"
    )
    assert "CACHE 65536" in schema_sql, f"Schema should specify CACHE 65536:\n{schema_sql}"


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "generator_cls", [AuroraDSQLPsycopgSchemaGenerator, AuroraDSQLAsyncpgSchemaGenerator]
)
@pytest.mark.parametrize(
    "field_cls,field_name",
    [
        (fields.IntField, "IntField"),
        (fields.SmallIntField, "SmallIntField"),
    ],
)
async def test_unsupported_int_pk_raises_error(
    initialized_models, generator_cls, field_cls, field_name
):
    """Test that IntField and SmallIntField PKs raise a helpful error."""
    generator = generator_cls(_create_mock_client())

    field = field_cls(primary_key=True)
    field.model_field_name = "id"

    with pytest.raises(ValueError) as exc_info:
        generator._get_pk_create_sql(field, "id", "")

    assert field_name in str(exc_info.value)
    assert "UUIDField" in str(exc_info.value)
    assert "BigIntField" in str(exc_info.value)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "generator_cls", [AuroraDSQLPsycopgSchemaGenerator, AuroraDSQLAsyncpgSchemaGenerator]
)
@pytest.mark.parametrize("field_cls", [fields.IntField, fields.SmallIntField])
async def test_non_generated_int_pk_allowed(initialized_models, generator_cls, field_cls):
    """Test that IntField/SmallIntField PKs with generated=False don't raise an error."""
    generator = generator_cls(_create_mock_client())

    field = field_cls(primary_key=True, generated=False)
    field.model_field_name = "id"

    # Should return empty string (no generated SQL needed).
    result = generator._get_pk_create_sql(field, "id", "")
    assert result == ""
