# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import unittest
from unittest.mock import MagicMock

import django
from django.conf import settings

from aurora_dsql_django.fields import DEFAULT_SEQUENCE_CACHE_SIZE, SequenceAutoField

if not settings.configured:
    settings.configure(
        USE_I18N=True,
        DATABASES={"default": {"ENGINE": "aurora_dsql_django"}},
    )
    django.setup()


class TestSequenceAutoField(unittest.TestCase):
    """Tests for SequenceAutoField custom field."""

    def setUp(self):
        """Set up mock connection for testing."""
        self.mock_connection = MagicMock()
        self.mock_connection.vendor = "dsql"
        self.mock_connection.settings_dict = {}

    def test_default_sequence_cache_size_constant(self):
        """Test that DEFAULT_SEQUENCE_CACHE_SIZE is set correctly."""
        self.assertEqual(DEFAULT_SEQUENCE_CACHE_SIZE, 65536)

    def test_db_type_returns_bigint_for_dsql(self):
        """Test that db_type returns 'bigint' for DSQL connections."""
        field = SequenceAutoField()
        db_type = field.db_type(self.mock_connection)
        self.assertEqual(db_type, "bigint")

    def test_db_type_suffix_with_default_cache_size(self):
        """Test db_type_suffix uses DEFAULT_SEQUENCE_CACHE_SIZE when no override."""
        field = SequenceAutoField()
        suffix = field.db_type_suffix(self.mock_connection)

        expected = f"GENERATED BY DEFAULT AS IDENTITY (CACHE {DEFAULT_SEQUENCE_CACHE_SIZE})"
        self.assertEqual(suffix, expected)

    def test_db_type_suffix_with_field_level_cache_size(self):
        """Test db_type_suffix uses field-level sequence_cache_size parameter."""
        custom_cache_size = 1024
        field = SequenceAutoField(sequence_cache_size=custom_cache_size)
        suffix = field.db_type_suffix(self.mock_connection)

        expected = f"GENERATED BY DEFAULT AS IDENTITY (CACHE {custom_cache_size})"
        self.assertEqual(suffix, expected)

    def test_db_type_suffix_with_connection_settings_cache_size(self):
        """Test db_type_suffix uses connection settings SEQUENCE_CACHE_SIZE."""
        connection_cache_size = 2048
        self.mock_connection.settings_dict["SEQUENCE_CACHE_SIZE"] = connection_cache_size

        field = SequenceAutoField()
        suffix = field.db_type_suffix(self.mock_connection)

        expected = f"GENERATED BY DEFAULT AS IDENTITY (CACHE {connection_cache_size})"
        self.assertEqual(suffix, expected)

    def test_db_type_suffix_field_level_overrides_connection_settings(self):
        """Test that field-level sequence_cache_size overrides connection settings."""
        field_cache_size = 512
        connection_cache_size = 2048

        self.mock_connection.settings_dict["SEQUENCE_CACHE_SIZE"] = connection_cache_size
        field = SequenceAutoField(sequence_cache_size=field_cache_size)
        suffix = field.db_type_suffix(self.mock_connection)

        expected = f"GENERATED BY DEFAULT AS IDENTITY (CACHE {field_cache_size})"
        self.assertEqual(suffix, expected)

    def test_db_type_suffix_priority_order(self):
        """Test the priority order: field-level > connection settings > default."""
        # Test 1: Only default
        field1 = SequenceAutoField()
        suffix1 = field1.db_type_suffix(self.mock_connection)
        self.assertIn(f"CACHE {DEFAULT_SEQUENCE_CACHE_SIZE}", suffix1)

        # Test 2: Connection settings override default
        self.mock_connection.settings_dict["SEQUENCE_CACHE_SIZE"] = 2048
        field2 = SequenceAutoField()
        suffix2 = field2.db_type_suffix(self.mock_connection)
        self.assertIn("CACHE 2048", suffix2)

        # Test 3: Field-level overrides connection settings
        field3 = SequenceAutoField(sequence_cache_size=512)
        suffix3 = field3.db_type_suffix(self.mock_connection)
        self.assertIn("CACHE 512", suffix3)

    def test_db_type_suffix_with_various_cache_sizes(self):
        """Test db_type_suffix with various cache size values."""
        test_values = [1, 65536, 65537, 100000]

        for cache_size in test_values:
            with self.subTest(cache_size=cache_size):
                field = SequenceAutoField(sequence_cache_size=cache_size)
                suffix = field.db_type_suffix(self.mock_connection)

                expected = f"GENERATED BY DEFAULT AS IDENTITY (CACHE {cache_size})"
                self.assertEqual(suffix, expected)

    def test_db_type_suffix_for_non_dsql_connection(self):
        """Test that db_type_suffix returns parent implementation for non-DSQL."""
        self.mock_connection.vendor = "postgresql"
        field = SequenceAutoField(sequence_cache_size=1024)
        suffix = field.db_type_suffix(self.mock_connection)

        # Should not contain IDENTITY clause for non-DSQL
        self.assertNotIn("IDENTITY", suffix)

    def test_sequence_cache_size_attribute_stored(self):
        """Test that sequence_cache_size is stored as instance attribute."""
        cache_size = 4096
        field = SequenceAutoField(sequence_cache_size=cache_size)

        self.assertEqual(field._sequence_cache_size, cache_size)

    def test_sequence_cache_size_none_by_default(self):
        """Test that sequence_cache_size is None when not provided."""
        field = SequenceAutoField()

        self.assertIsNone(field._sequence_cache_size)

    def test_field_initialization_with_other_parameters(self):
        """Test that SequenceAutoField works with other field parameters."""
        field = SequenceAutoField(primary_key=True, sequence_cache_size=2048, verbose_name="Custom ID")

        self.assertTrue(field.primary_key)
        self.assertEqual(field._sequence_cache_size, 2048)
        self.assertEqual(field.verbose_name, "Custom ID")

    def test_field_initialization_preserves_parent_behavior(self):
        """Test that SequenceAutoField preserves BigAutoField behavior."""
        field = SequenceAutoField()

        # Should inherit from BigAutoField
        from django.db import models

        self.assertIsInstance(field, models.BigAutoField)


if __name__ == "__main__":
    unittest.main()
