// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1
package software.amazon.dsql.hibernate.dialect;

import org.hibernate.dialect.identity.IdentityColumnSupportImpl;

/**
 * Identity column support for Aurora DSQL.
 *
 * <p>Aurora DSQL supports identity columns with a mandatory {@code CACHE} parameter on the
 * underlying sequence. This class generates the appropriate DDL for identity columns.
 */
public class AuroraDSQLIdentitySupport extends IdentityColumnSupportImpl {

  private final int sequenceCacheSize;

  public AuroraDSQLIdentitySupport(int sequenceCacheSize) {
    this.sequenceCacheSize = sequenceCacheSize;
  }

  @Override
  public boolean supportsIdentityColumns() {
    return true;
  }

  @Override
  public boolean hasDataTypeInIdentityColumn() {
    return false;
  }

  @Override
  public String getIdentityColumnString(int type) {
    return "bigint generated by default as identity (START WITH 1 INCREMENT BY 1 CACHE "
        + sequenceCacheSize
        + ")";
  }
}
