// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1
package software.amazon.dsql.hibernate.dialect;

import org.hibernate.dialect.identity.IdentityColumnSupportImpl;

public class AuroraDSQLIdentitySupport extends IdentityColumnSupportImpl {

    private final int sequenceCacheSize;

    public AuroraDSQLIdentitySupport(int sequenceCacheSize) {
        this.sequenceCacheSize = sequenceCacheSize;
    }

    @Override
    public boolean supportsIdentityColumns() {
        return true;
    }

    @Override
    public boolean hasDataTypeInIdentityColumn() {
        return false;
    }

    @Override
    public String getIdentityColumnString(int type) {
        return "bigint generated by default as identity (START WITH 1 INCREMENT BY 1 CACHE " + sequenceCacheSize + ")";
    }

}
