using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Amazon.AuroraDsql.EntityFrameworkCore.Infrastructure;

/// <summary>
/// Model-finalizing convention that auto-applies gen_random_uuid() defaults for UUID
/// primary keys and GENERATED BY DEFAULT AS IDENTITY for long (BIGINT) primary keys
/// when no explicit value generation strategy is configured.
/// </summary>
internal sealed class DsqlPrimaryKey : IModelFinalizingConvention
{
    private readonly bool _useIdentityColumns;
    private readonly int _identityCacheSize;

    public DsqlPrimaryKey(bool useIdentityColumns, int identityCacheSize)
    {
        _useIdentityColumns = useIdentityColumns;
        _identityCacheSize = identityCacheSize;
    }

    public void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
    {
        foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())
        {
            if (entityType.IsOwned()) continue;

            var pk = entityType.FindPrimaryKey();
            if (pk == null) continue;

            foreach (var property in pk.Properties)
            {
                if (property.ClrType == typeof(Guid)
                    && property.GetDefaultValueSql() == null
                    && property.GetValueGenerationStrategy() == NpgsqlValueGenerationStrategy.None)
                {
                    property.Builder.HasDefaultValueSql("gen_random_uuid()");
                    property.Builder.ValueGenerated(ValueGenerated.OnAdd);
                }
                else if (_useIdentityColumns
                         && property.ClrType == typeof(long)
                         && property.GetDefaultValueSql() == null
                         && property.GetValueGenerationStrategy() == NpgsqlValueGenerationStrategy.None)
                {
                    property.SetValueGenerationStrategy(NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                    property.Builder.HasIdentityOptions(numbersToCache: _identityCacheSize);
                    property.Builder.ValueGenerated(ValueGenerated.OnAdd);
                }
            }
        }
    }
}

internal sealed class DsqlConventionSetPlugin : IConventionSetPlugin
{
    private readonly bool _useIdentityColumns;
    private readonly int _identityCacheSize;

    public DsqlConventionSetPlugin(bool useIdentityColumns, int identityCacheSize)
    {
        _useIdentityColumns = useIdentityColumns;
        _identityCacheSize = identityCacheSize;
    }

    public ConventionSet ModifyConventions(ConventionSet conventionSet)
    {
        conventionSet.ModelFinalizingConventions.Add(
            new DsqlPrimaryKey(_useIdentityColumns, _identityCacheSize));
        return conventionSet;
    }
}

internal sealed class DsqlOptionsExtension : IDbContextOptionsExtension
{
    public bool UseIdentityColumns { get; init; }
    public int IdentityCacheSize { get; init; } = DsqlDbContextOptionsBuilder.DefaultIdentityCacheSize;

    private ExtInfo? _info;
    public DbContextOptionsExtensionInfo Info => _info ??= new ExtInfo(this);

    public void ApplyServices(IServiceCollection services)
    {
        services.TryAddEnumerable(
            ServiceDescriptor.Scoped<IConventionSetPlugin, DsqlConventionSetPlugin>(
                _ => new DsqlConventionSetPlugin(UseIdentityColumns, IdentityCacheSize)));
    }

    public void Validate(IDbContextOptions options) { }

    private sealed class ExtInfo : DbContextOptionsExtensionInfo
    {
        public ExtInfo(IDbContextOptionsExtension extension) : base(extension) { }
        public override bool IsDatabaseProvider => false;
        public override string LogFragment => "using DsqlPK ";
        public override int GetServiceProviderHashCode()
        {
            var ext = (DsqlOptionsExtension)Extension;
            return HashCode.Combine(ext.UseIdentityColumns, ext.IdentityCacheSize);
        }
        public override bool ShouldUseSameServiceProvider(DbContextOptionsExtensionInfo other)
            => other is ExtInfo o
               && ((DsqlOptionsExtension)o.Extension).UseIdentityColumns == ((DsqlOptionsExtension)Extension).UseIdentityColumns
               && ((DsqlOptionsExtension)o.Extension).IdentityCacheSize == ((DsqlOptionsExtension)Extension).IdentityCacheSize;
        public override void PopulateDebugInfo(IDictionary<string, string> debugInfo)
        {
            var ext = (DsqlOptionsExtension)Extension;
            debugInfo["Dsql:IdentityColumns"] = ext.UseIdentityColumns.ToString();
            debugInfo["Dsql:CacheSize"] = ext.IdentityCacheSize.ToString();
        }
    }
}
