namespace Amazon.AuroraDsql.EntityFrameworkCore.Infrastructure;

/// <summary>
/// Allows configuration of DSQL-specific options.
/// </summary>
public sealed class DsqlDbContextOptionsBuilder
{
    /// <summary>Default sequence cache size for IDENTITY columns.
    /// Large cache (65,536) distributes ID generation across DSQL nodes,
    /// avoiding hot-key contention on the sequence.</summary>
    public const int DefaultIdentityCacheSize = 65536;

    internal int? MaxRetryCount { get; private set; }
    internal TimeSpan? MaxRetryDelay { get; private set; }
    internal bool UseIdentityColumns { get; private set; }
    internal int IdentityCacheSize { get; private set; } = DefaultIdentityCacheSize;

    /// <summary>
    /// Sets the maximum number of retry attempts for OCC conflicts.
    /// Default is 6.
    /// </summary>
    public DsqlDbContextOptionsBuilder SetMaxRetryCount(int maxRetryCount)
    {
        if (maxRetryCount < 0)
            throw new ArgumentOutOfRangeException(nameof(maxRetryCount));

        MaxRetryCount = maxRetryCount;
        return this;
    }

    /// <summary>
    /// Sets the maximum delay between retries.
    /// Default is 30 seconds.
    /// </summary>
    public DsqlDbContextOptionsBuilder SetMaxRetryDelay(TimeSpan maxRetryDelay)
    {
        if (maxRetryDelay < TimeSpan.Zero)
            throw new ArgumentOutOfRangeException(nameof(maxRetryDelay));

        MaxRetryDelay = maxRetryDelay;
        return this;
    }

    /// <summary>
    /// Enables IDENTITY column support for long (BIGINT) primary keys.
    /// Uses GENERATED BY DEFAULT AS IDENTITY with the specified cache size.
    /// </summary>
    public DsqlDbContextOptionsBuilder EnableIdentityColumns(int cacheSize = DefaultIdentityCacheSize)
    {
        if (cacheSize < 1)
            throw new ArgumentOutOfRangeException(nameof(cacheSize));

        UseIdentityColumns = true;
        IdentityCacheSize = cacheSize;
        return this;
    }
}
