# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Custom fields with behavior defined for Aurora DSQL."""

from __future__ import annotations

from tortoise import fields

DEFAULT_SEQUENCE_CACHE_SIZE = 65536


def _get_identity_sql(sequence_cache_size: int) -> str:
    return (
        f"BIGINT GENERATED BY DEFAULT AS IDENTITY "
        f"(CACHE {sequence_cache_size}) NOT NULL PRIMARY KEY"
    )


class BigIntField(fields.BigIntField):
    """BigIntField with configurable identity cache size for DSQL.

    Args:
        sequence_cache_size: Identity column cache size. Must be 1 or >= 65536.
            Defaults to 65536 for high throughput.
    """

    def __init__(self, sequence_cache_size: int = DEFAULT_SEQUENCE_CACHE_SIZE, **kwargs):
        super().__init__(**kwargs)
        self._sequence_cache_size = sequence_cache_size

    def get_for_dialect(self, dialect: str, key: str):
        if key == "GENERATED_SQL" and self.pk:
            return _get_identity_sql(self._sequence_cache_size)
        return super().get_for_dialect(dialect, key)
