# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Custom field types for Aurora DSQL that use IDENTITY columns with configurable CACHE sizes.

Aurora DSQL requires explicit CACHE configuration for IDENTITY columns. These field types
automatically generate the appropriate SQL with CACHE clauses based on the SEQUENCE_CACHE_SIZE
setting in your database configuration  (defaults to 65536 if not specified).
"""

from django.db import models

DEFAULT_SEQUENCE_CACHE_SIZE = 65536


class SequenceAutoField(models.BigAutoField):
    """
    BigAutoField that uses IDENTITY sequences with CACHE for Aurora DSQL.

    Args:
        sequence_cache_size: Optional cache size for the IDENTITY sequence.
                           If not provided, uses SEQUENCE_CACHE_SIZE from database settings
                           (defaults to DEFAULT_SEQUENCE_CACHE_SIZE if not specified).
    """

    def __init__(self, *args, sequence_cache_size=None, **kwargs):
        self._sequence_cache_size = sequence_cache_size
        super().__init__(*args, **kwargs)

    def db_type(self, connection):
        if connection.vendor == "dsql":
            return "bigint"
        return super().db_type(connection)

    def db_type_suffix(self, connection):
        if connection.vendor == "dsql":
            cache_size = self._sequence_cache_size or connection.settings_dict.get(
                "SEQUENCE_CACHE_SIZE", DEFAULT_SEQUENCE_CACHE_SIZE
            )
            return f"GENERATED BY DEFAULT AS IDENTITY (CACHE {cache_size})"
        return super().db_type_suffix(connection)
